version: '3.5'

services:
  core-authentications-application:
    image: core-authentications-application:latest
    container_name: core-authentications-application
    restart: unless-stopped
    build:
      context: ../../..
      dockerfile: apps/core-authentications/devops/Dockerfile
    depends_on:
      - core-authentications-database
      - core-authentications-cache
    links:
      - core-authentications-database
      - core-authentications-cache
    networks:
      - core-authentications
      - zozoboom
    ports:
      - 127.0.0.1:4002:3000
    environment:
      HTTP_PORT: 3000
      HTTP_CORS_ORIGIN: 'https://admin.zozoboom.com,https://dev.zozoboom.com'
      RPC_SERVERS: 'nats://zozoboom-rpc-gateway:4222'
      RPC_QUEUE: 'core-authentications'
      DB_HOST: 'core-authentications-database'
      DB_PORT: 27017
      DB_NAME: ${MONGO_DB_DATABASE}
      DB_USERNAME: ${MONGO_DB_USERNAME}
      DB_PASSWORD: ${MONGO_DB_PASSWORD}
      CACHE_HOST: 'core-authentications-cache'
      CACHE_PORT: 6379
      CACHE_TTL: 900
      SECURITY_EMAIL_ADMIN_APPROVE: 'sllavvicc@gmail.com'
      SECURITY_FORGOT_TOKEN_SALT: ${SECURITY_FORGOT_TOKEN_SALT}
      SECURITY_ACCESS_TOKEN_SALT: ${SECURITY_ACCESS_TOKEN_SALT}
      SECURITY_REFRESH_TOKEN_SALT: ${SECURITY_REFRESH_TOKEN_SALT}

  core-authentications-database:
    image: mongo:latest
    container_name: core-authentications-database
    restart: unless-stopped
    command: mongod
    ports:
      - 4003:27017
    networks:
      - core-authentications
      - core-authentications-statistics
    volumes:
      - ./docker-entrypoint-initdb:/docker-entrypoint-initdb.d
      - database-data:/data/db
      - database-config:/data/configdb
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
      MONGO_DB_DATABASE: ${MONGO_DB_DATABASE}
      MONGO_DB_USERNAME: ${MONGO_DB_USERNAME}
      MONGO_DB_PASSWORD: ${MONGO_DB_PASSWORD}

  core-authentications-cache:
    image: redis:latest
    container_name: core-authentications-cache
    restart: unless-stopped
    networks:
      - core-authentications
    volumes:
      - redis:/var/lib/redis
      - redis-data:/data
      - redis-config:/usr/local/etc/redis/redis.conf

volumes:
  database-data:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: /var/www/docker-storage/core-authentications/database-data
  database-config:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: /var/www/docker-storage/core-authentications/database-config
  redis:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: /var/www/docker-storage/core-authentications/redis
  redis-data:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: /var/www/docker-storage/core-authentications/redis-data
  redis-config:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: /var/www/docker-storage/core-authentications/redis-config

networks:
  core-authentications:
    name: core-authentications
    external: true
  core-authentications-statistics:
    name: core-authentications-statistics
    external: true
  zozoboom:
    name: zozoboom
    external: true
