version: '3.5'

services:
  core-authentications-application:
    image: core-authentications-application:latest
    container_name: core-authentications-application
    restart: unless-stopped
    build:
      context: ../../..
      dockerfile: apps/core-authentications/devops/Dockerfile
    depends_on:
      - core-authentications-database
      - core-authentications-cache
    links:
      - core-authentications-database
      - core-authentications-cache
    networks:
      - core-authentications
      - zozoboom
    environment:
      HTTP_PORT: 3000
      HTTP_CORS_ORIGIN: '*,http://localhost:4200'
      RPC_SERVERS: 'nats://zozoboom-rpc-gateway:4222'
      RPC_QUEUE: 'core-authentications'
      DB_HOST: 'core-authentications-database'
      DB_PORT: 27017
      DB_NAME: 'zozoboom'
      DB_USERNAME: 'zozoboom'
      DB_PASSWORD: 'zozoboom'
      CACHE_HOST: 'core-authentications-cache'
      CACHE_PORT: 6379
      CACHE_TTL: 900
      SECURITY_EMAIL_ADMIN_APPROVE: 'sllavvicc@gmail.com'
      SECURITY_FORGOT_TOKEN_SALT: 'forgotTokenTTL'
      SECURITY_ACCESS_TOKEN_SALT: 'accessTokenSalt'
      SECURITY_REFRESH_TOKEN_SALT: 'refreshTokenSalt'

  core-authentications-database:
    image: mongo:latest
    container_name: core-authentications-database
    restart: unless-stopped
    command: mongod
    ports:
      - 3002:27017
    networks:
      - core-authentications
      - core-authentications-statistics
    volumes:
      - ./docker-entrypoint-initdb:/docker-entrypoint-initdb.d
      - ${HOME}/docker-storage/zozoboom/core-authentications/database-data:/data/db
      - ${HOME}/docker-storage/zozoboom/core-authentications/database-config:/data/configdb
    environment:
      MONGO_INITDB_ROOT_USERNAME: 'zozoboom'
      MONGO_INITDB_ROOT_PASSWORD: 'zozoboom'
      MONGO_DB_DATABASE: 'zozoboom'
      MONGO_DB_USERNAME: 'zozoboom'
      MONGO_DB_PASSWORD: 'zozoboom'

  core-authentications-cache:
    image: redis:latest
    container_name: core-authentications-cache
    restart: unless-stopped
    ports:
      - 3003:6379
    networks:
      - core-authentications
    volumes:
      - ${HOME}/docker-storage/zozoboom/core-authentications/redis:/var/lib/redis
      - ${HOME}/docker-storage/zozoboom/core-authentications/redis-data:/data
      - ${HOME}/docker-storage/zozoboom/core-authentications/redis-config:/usr/local/etc/redis/redis.conf

networks:
  core-authentications:
    name: core-authentications
    external: true
  core-authentications-statistics:
    name: core-authentications-statistics
    external: true
  zozoboom:
    name: zozoboom
    external: true
